# Generated by Django 5.0.6 on 2024-06-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('photo', models.CharField(max_length=200, null=True, verbose_name='Rasm file_id')),
                ('price', models.DecimalField(decimal_places=2, max_digits=200, verbose_name='Narxi')),
                ('description', models.TextField(max_length=300, verbose_name='Mahsulot haqida')),
                ('category_code', models.CharField(max_length=200, verbose_name='Kategoriya kodi')),
                ('category_name', models.CharField(max_length=200, verbose_name='Category Nomi')),
                ('subcategory_code', models.CharField(max_length=34, verbose_name='Ost-kategoriya kodi')),
                ('subcategory_name', models.CharField(max_length=30, verbose_name='Ost-kategoriya nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Full Name')),
                ('username', models.CharField(max_length=30, null=True, unique=True, verbose_name='Username')),
                ('telegram_id', models.PositiveBigIntegerField(unique=True, verbose_name='Telegram Id')),
                ('create_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
